version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - slick-network
    ports:
      - 15432:5432
networks:
  slick-network:

